Repository Class-Widgets/Class-Widgets, pull requests merged in 2025-08, with the labels that each got.

#805 feat(weather): Open-Meteo支持
  config/data/open_meteo_status.json
  config/data/weather_api.json
  main.py
  menu.py
  network_thread.py
  requirements.txt
  view/menu/custom.ui
  weather.py
Labels: test/accepted/any

#816 fix: 窗口状态热生效
  extra_menu.py
  list_.py
  main.py
  menu.py
  tip_toast.py
  utils.py
  view/menu/advance.ui
Labels: test/required/MacOS, test/accepted/Linux, test/accepted/Windows

#810 chore: Translations update from Hosted Weblate [skip ci]
  i18n/base.ts
  i18n/en_US.ts
  i18n/ja_JP.ts
  i18n/zh_CN.ts
  i18n/zh_HK.ts
  ui/default/i18n/base.ts
Labels: i18n_translate

#876 feat: apply basic_dirs
  .github/workflows/build.yml
  basic_dirs.py
  conf.py
  config/config.json
  config/default.json
  config/mirror.json
  cses_mgr.py
  data/amap_weather.db
  data/amap_weather_status.json
  data/completed_i18n.json
  data/default_config.json
  data/default_schedule.json
  data/mirror.json
  data/open_meteo_status.json
  data/qq_weather_status.json
  data/qweather_status.json
  data/subject.json
  data/weather_api.json
  data/xiaomi_weather.db
  data/xiaomi_weather_status.json
  extra_menu.py
  file.py
  generate_speech.py
  i18n_manager.py
  list_.py
  main.py
  menu.py
  network_thread.py
  play_audio.py
  plugin.py
  plugin_plaza.py
  tip_toast.py
  utils.py
  weather.py
Labels: 配置
