Repository Class-Widgets/Class-Widgets, pull requests merged in 2025-06, with the labels that each got.

#635 fix: 换课菜单不适配触摸操控
  view/extra_menu.ui
Labels: test/required/any

#642 feat: 可跟踪的版本信息管理
  .github/workflows/build.yml
  .github/workflows/build_pyinstaller.yml
  conf.py
  config/default_config.json
  cses_mgr.py
  extra_menu.py
  file.py
  list_.py
  main.py
  menu.py
  network_thread.py
  view/menu/about.ui
Labels: test/accepted/any

#595 feat: 支持 TTS 播报
  .gitignore
  config/default_config.json
  generate_speech.py
  main.py
  menu.py
  network_thread.py
  play_audio.py
  tip_toast.py
  view/menu/sound.ui
  view/menu/tts_settings.ui
Labels: test/required/MacOS, test/accepted/Linux, test/accepted/Windows

#650 fix: 限制课程名称显示长度
  config/data/subject.json
  main.py
  utils.py
Labels: test/required/any

#682 ci: 妈生的 schedule 再见。
  .github/workflows/build.yml
Labels: 爱吃猫的

#663 feat: i18n
  config/default_config.json
  main.py
  menu.py
  ui/default/dark/i18n/zh_CN.qm
  ui/default/dark/i18n/zh_CN.ts
  ui/default/i18n/zh_CN.qm
  ui/default/i18n/zh_CN.ts
  ui/hoshino/dark/i18n/zh_CN.ts
  ui/hoshino/i18n/zh_CN.ts
  ui/minimize/dark/i18n/zh_CN.ts
  ui/minimize/i18n/zh_CN.ts
  ui/shiroko/dark/i18n/zh_CN.ts
  ui/shiroko/i18n/zh_CN.ts
  view/i18n/zh_CN.qm
  view/i18n/zh_CN.ts
  view/menu/advance.ui
Labels: 优先级：低, Ciallo~

#690 feat: 界面多语言
  Scripts/i18n/release.ps1
  Scripts/i18n/update.ps1
  i18n/zh_CN.qm
  i18n/zh_CN.ts
  menu.py
  view/i18n/zh_CN.qm
  view/i18n/zh_CN.ts
Labels: feat, i18n

#508 refactor: 配置文件栏 & 从互联网获取课表
  config/default.json
  config/schedule/新课表 - 1.json
  file.py
  list_.py
  menu.py
  network_thread.py
  view/menu/advance.ui
  view/menu/configs.ui
  view/menu/file_item.ui
  view/menu/help.ui
Labels: Ciallo~

#726 feat(TTS): 多语言支持(预留)
  config/default_config.json
  file.py
  generate_speech.py
  utils.py
Labels: i18n
