Repository Class-Widgets/Class-Widgets, pull requests merged in 2025-09, with the labels that each got.

#927 ci: matrix-choice
  .github/ISSUE_TEMPLATE/I18nReport.yml
  .github/workflows/build.yml
  README.md
  data/default_schedule.json
  data/open_meteo_status.json
  docs/readme/README.en_US.md
  docs/readme/README.ja.md
Labels: github_actions

#924 feat: 在交互窗口后重新激活先前的窗口
  main.py
  utils.py
Labels: test/required/Linux

#957 ci: msi打包
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/sign.yml
  conf.py
  installer/ClassWidgets.wxs
  installer/cleanup.vbs
  main.py
  menu.py
  utils.py
Labels: 等待验证
