Repository Class-Widgets/Class-Widgets, pull requests merged in 2025-07, with the labels that each got.

#749 docs: 添加i18n issue模板
  .github/ISSUE_TEMPLATE/BugReport.yml
  .github/ISSUE_TEMPLATE/I18nReport.yml
  .github/ISSUE_TEMPLATE/PluginsRequest.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: Doc, i18n

#771 docs(readme): 优化“安装和使用”描述(中,英文)
  README.md
  docs/readme/README.en_US.md
  docs/readme/README.ja.md
Labels: i18n

#773 chore: 使用锁机制替代多开判断
  main.py
  utils.py
Labels: test/required/MacOS, test/accepted/Linux, test/accepted/Windows

#781 refactor(build)!: 重构构建流程
  .github/workflows/build.yml
  .github/workflows/build_macos.yml
  .github/workflows/build_pyinstaller.yml
  .github/workflows/release.yml
Labels: test/required/any

#792 ci(i18n): 添加i18n自动更新 [skip ci]
  .github/workflows/i18n.yml
  ui/default/widget-time.ui
Labels: i18n

#796 fix(time): 时间精度造成的通知问题
  main.py
  utils.py
Labels: test/accepted/any

#807 Translations update from Hosted Weblate
  i18n/en_US.ts
  i18n/zh_CN.ts
  i18n/zh_HK.ts
  ui/default/i18n/zh_CN.ts
Labels: i18n_translate
